# Generated by Django 5.0.6 on 2024-06-07 17:15

import django.db.models.deletion
import employee_app.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hno', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=5000)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificationName', models.CharField(max_length=255)),
                ('percentage', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'qualification',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('fromDate', models.DateField(blank=True, null=True)),
                ('toDate', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'work_experience',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phoneNo', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None)),
                ('photo', models.ImageField(default='Users/blank_profile.webp', null=True, upload_to=employee_app.models.rename)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee_app.address')),
                ('projects', models.ForeignKey(db_column='id', default=1, on_delete=django.db.models.deletion.CASCADE, to='employee_app.project', verbose_name='project')),
                ('qualifications', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee_app.qualification')),
                ('workExperience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee_app.workexperience')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
